"use strict";

/*
|--------------------------------------------------------------------------
| WALAWWA DOWNLOAD PAGE
|--------------------------------------------------------------------------
|
| URL:
|
| https://your-site.web.app/?start=CODE
|
| The CODE is generated by the Telegram bot.
|
| Later, replace API_BASE_URL with your Northflank backend.
|
|--------------------------------------------------------------------------
*/


// ============================================================
// CONFIGURATION
// ============================================================

const API_BASE_URL = "https://YOUR-NORTHFLANK-API";


const COUNTDOWN_SECONDS = 5;


// ============================================================
// ELEMENTS
// ============================================================

const countdownElement =
    document.getElementById("countdown");

const countdownTextElement =
    document.getElementById("countdown-text");

const downloadButton =
    document.getElementById("download-button");

const buttonText =
    document.getElementById("button-text");

const errorMessage =
    document.getElementById("error-message");


// ============================================================
// GET CODE
// ============================================================

function getDownloadCode() {

    const params =
        new URLSearchParams(
            window.location.search
        );

    const code =
        params.get("start");

    if (!code) {
        return null;
    }

    return code.trim();
}


// ============================================================
// SHOW ERROR
// ============================================================

function showError(message) {

    if (!errorMessage) {
        return;
    }

    errorMessage.textContent = message;

    errorMessage.hidden = false;

    if (downloadButton) {

        downloadButton.disabled = true;
    }

}


// ============================================================
// HIDE ERROR
// ============================================================

function hideError() {

    if (!errorMessage) {
        return;
    }

    errorMessage.hidden = true;

}


// ============================================================
// COUNTDOWN
// ============================================================

function startCountdown() {

    let remaining =
        COUNTDOWN_SECONDS;

    countdownElement.textContent =
        remaining;

    countdownTextElement.textContent =
        "Please wait...";


    const timer =
        setInterval(() => {

            remaining--;

            countdownElement.textContent =
                remaining;


            countdownElement.classList.add(
                "tick"
            );


            setTimeout(() => {

                countdownElement.classList.remove(
                    "tick"
                );

            }, 180);


            if (remaining <= 0) {

                clearInterval(timer);

                unlockDownload();

            }

        }, 1000);
}


// ============================================================
// UNLOCK DOWNLOAD
// ============================================================

function unlockDownload() {

    countdownElement.textContent =
        "✓";

    countdownTextElement.textContent =
        "Your download is ready";


    downloadButton.disabled =
        false;


    buttonText.textContent =
        "Download File";


    downloadButton.setAttribute(
        "aria-label",
        "Download File"
    );

}


// ============================================================
// DOWNLOAD
// ============================================================

async function downloadFile() {

    const code =
        getDownloadCode();

    if (!code) {

        showError(
            "Invalid download link."
        );

        return;
    }


    if (
        !API_BASE_URL ||
        API_BASE_URL.includes(
            "YOUR-NORTHFLANK-API"
        )
    ) {

        showError(
            "Download service is not connected yet."
        );

        return;
    }


    downloadButton.disabled =
        true;


    buttonText.textContent =
        "Preparing download...";


    hideError();


    try {

        /*
         * The Northflank API will eventually
         * receive:
         *
         * GET /download?code=XXXX
         *
         * It can then retrieve the corresponding
         * Telegram file information from Firebase
         * and provide the download.
         */

        const url =
            API_BASE_URL.replace(
                /\/$/,
                ""
            )
            + "/download?code="
            + encodeURIComponent(code);


        /*
         * Navigate to the backend rather than
         * exposing Firebase credentials or
         * Telegram credentials in the browser.
         */

        window.location.href = url;


    } catch (error) {

        console.error(
            "Download error:",
            error
        );


        showError(
            "Download failed. Please try again."
        );


        downloadButton.disabled =
            false;


        buttonText.textContent =
            "Download File";

    }

}


// ============================================================
// BUTTON EVENT
// ============================================================

downloadButton.addEventListener(
    "click",
    downloadFile
);


// ============================================================
// INITIALIZE
// ============================================================

function initialize() {

    const code =
        getDownloadCode();


    if (!code) {

        countdownElement.textContent =
            "!";

        countdownTextElement.textContent =
            "Invalid download link";


        showError(
            "Please open a valid WALAWWA download link."
        );

        return;
    }


    hideError();


    /*
     * Start the five-second countdown.
     */

    startCountdown();

}


// ============================================================
// START
// ============================================================

initialize();
